[kernel]
pkgs = { linux-zen linux-firmware sof-firmware base base-devel }

[bootmgr]
pkgs = { grub efibootmgr }

[desktop]
metapkgs = { cinnamon }
pkgs = { firefox lightdm-gtk-greeter xclip maim papirus-icon-theme }

[packages]
pkgs = { sudo neovim fish fastfetch git discord gparted jdk25-openjdk prismlauncher pfetch cmatrix pcmanfm }
#blacklist = { gnome-weather gnome-calendar gnome-font-viewer epiphany baobab gnome-maps gnome-music gnome-tour yelp gnome-characters gnome-contacts gnome-connections gnome-disk-utility gnome-user-docs }

[fonts]
pkgs = { ttf-iosevka-nerd ttf-adwaitamono-nerd }

[services]
pkgs = { dbus networkmanager cronie turnstile pipewire wireplumber pipewire-pulse lightdm }
enabled = { dbus elogind NetworkManager cronie turnstiled lightdm }

[drivers]
pkgs = { vulkan-intel xf86-video-intel libva-intel-driver intel-media-driver lib32-libva-intel-driver lib32-vulkan-intel intel-ucode lib32-mesa }

[sudo]
wheel = allowed no_sudo_password

[hostname]
hostname = artix

[timezone]
timezone = Europe/Bucharest

[user:beamy]
groups = { wheel audio video input }
shell = /usr/bin/fish
[user-services]
beamy = { pipewire wireplumber pipewire-pulse }

init = dinit
